// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozrtkarteknjfmwotfoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96cnRrYXJ0ZWtuamZtd290Zm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMTA5NzQsImV4cCI6MjA2MzU4Njk3NH0.0t-hhbGMBUGG84-vJZzqaxfRKwtyc3KFg_xRi0xCd2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);